# Generated by Django 5.2.6 on 2025-09-04 08:31

import audiobooks.models
import audiobooks.storages_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cover_image', models.FileField(storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.cover_upload_path)),
                ('transcription_file', models.FileField(blank=True, null=True, storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.transcription_upload_path)),
                ('audio_file', models.FileField(storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.audio_upload_path)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
