# Generated by Django 5.2.6 on 2025-09-04 03:34

import storages.backends.azure_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='cover_image',
            field=models.ImageField(default='sda', storage=storages.backends.azure_storage.AzureStorage(), upload_to='covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiobook',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='transcription_file',
            field=models.FileField(default='asda', storage=storages.backends.azure_storage.AzureStorage(), upload_to='transcriptions/'),
            preserve_default=False,
        ),
    ]
