# Generated by Django 5.2.6 on 2025-09-04 08:48

import audiobooks.models
import audiobooks.storages_backends
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='audio_file',
        ),
        migrations.CreateModel(
            name='AudiobookFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.audio_upload_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='audiobooks.audiobook')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
