# Generated by Django 5.2.6 on 2025-09-04 03:50

import audiobooks.models
import audiobooks.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0002_audiobook_cover_image_audiobook_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='audio_file',
            field=models.FileField(default='sda', storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.audio_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='cover_image',
            field=models.FileField(storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.cover_upload_path),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='transcription_file',
            field=models.FileField(storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.transcription_upload_path),
        ),
    ]
