# Generated by Django 5.2.6 on 2025-09-05 03:00

import audiobooks.models
import audiobooks.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0002_remove_audiobook_audio_file_audiobookfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='transcription_file',
        ),
        migrations.AlterField(
            model_name='audiobookfile',
            name='file',
            field=models.FileField(storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.transcription_upload_path),
        ),
    ]
