# Generated by Django 5.2.6 on 2025-09-04 04:15

import audiobooks.models
import audiobooks.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0003_audiobook_audio_file_alter_audiobook_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='transcription_file',
            field=models.FileField(blank=True, null=True, storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.transcription_upload_path),
        ),
    ]
