# Generated by Django 5.2.6 on 2025-09-05 03:01

import audiobooks.models
import audiobooks.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0003_remove_audiobook_transcription_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobookfile',
            name='transcription_file',
            field=models.FileField(default='sda', storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.transcription_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiobookfile',
            name='file',
            field=models.FileField(storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.audio_upload_path),
        ),
    ]
