# Generated by Django 5.2.6 on 2025-09-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0004_alter_audiobook_transcription_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=6),
            preserve_default=False,
        ),
    ]
