# Generated by Django 5.2.6 on 2025-09-05 03:01

import audiobooks.models
import audiobooks.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0004_audiobookfile_transcription_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookfile',
            name='transcription_file',
            field=models.FileField(blank=True, null=True, storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.transcription_upload_path),
        ),
    ]
