# Generated by Django 5.2.6 on 2025-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0005_audiobook_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
