# Generated by Django 5.2.6 on 2025-09-05 03:21

import audiobooks.models
import audiobooks.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0005_alter_audiobookfile_transcription_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='transcription_file',
            field=models.FileField(blank=True, null=True, storage=audiobooks.storages_backends.AzureAudiobookStorage(), upload_to=audiobooks.models.transcription_upload_path),
        ),
    ]
