# Generated by Django 5.2.6 on 2025-09-06 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0006_audiobook_transcription_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobookfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
