# Generated by Django 5.2.6 on 2025-09-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0007_audiobookfile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobookfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
